<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Consulta Processo</title>

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Estilos -->
    <link href="<?=STATIC_URL?>/bootstrap.min.css" rel="stylesheet">
    <link href="<?=STATIC_URL?>/global.css" rel="stylesheet">
    <link href="<?=STATIC_URL?>/index.css" rel="stylesheet">

    <!-- Scripts -->
    <script type="text/javascript" src="<?= STATIC_URL?>/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="<?= STATIC_URL?>/bootstrap.js"></script>
    <script type="text/javascript" src="<?= STATIC_URL?>/bootbox.min.js"></script>
    <script type="text/javascript" src="<?= STATIC_URL?>/funcoes.js"></script>

  </head>

  <body>

    <!-- Container -->

    <div>
      <!-- Barra de navegação -->
        <div id="topo">
                <!-- Opções de Menu -->

                <a href="<?= SITE_URL ?>/consulta/" class="brand">
                    
                </a>
        </div>
